---
project_name: golangci-lint

release:
  footer: >-
    apt and dnf/yum package repositories are available at
    [Packagecloud](https://packagecloud.io/golangci/golangci-lint).

builds:
  - binary: golangci-lint
    goos:
      - darwin
      - windows
      - linux
      - freebsd
      - netbsd
      - illumos
    goarch:
      - amd64
      - arm64
      - arm
      - 386
      - ppc64le
      - s390x
      - mips64
      - mips64le
      - riscv64
      - loong64
    goarm:
      - 6
      - 7
    gomips:
      - hardfloat
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: 386
      - goos: freebsd
        goarch: arm64
    main: ./cmd/golangci-lint/
    flags:
      - -trimpath
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '(?i)^docs?:'
      - '(?i)^docs\([^:]+\):'
      - '(?i)^docs\[[^:]+\]:'
      - '^tests?:'
      - '(?i)^dev:'
      - '^build\(deps\): bump .* in /docs \(#\d+\)'
      - '^build\(deps\): bump .* in /\.github/peril \(#\d+\)'
      - Merge pull request
      - Merge branch

source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Version }}-source'

nfpms:
  -
    id: golangci-lint-nfpms
    package_name: golangci-lint
    file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    homepage: https://golangci-lint.run/
    maintainer: "golangci-lint Team <golangci-releaser@users.noreply.github.com>"
    description: Fast linters Runner for Go
    license: GPLv3
    section: devel
    formats:
      - deb
      - rpm
    umask: 0o022
    overrides:
      deb:
        contents:
          - src: LICENSE
            dst: /usr/share/doc/golangci-lint/copyright
          - src: README.md
            dst: /usr/share/doc/golangci-lint/README.md
        recommends:
          - golang-go
      rpm:
        contents:
          - src: LICENSE
            dst: /usr/share/doc/golangci-lint/LICENSE
            type: license
          - src: README.md
            dst: /usr/share/doc/golangci-lint/README.md
            type: readme
        recommends:
          - /usr/bin/go
    rpm:
      group: Development/Tools
