version: 2

project_name: golangci-lint

builds:
  - binary: golangci-lint
    main: ./cmd/golangci-lint/
    flags:
      - -trimpath
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats: [ 'tar.gz' ]
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md

snapshot:
  version_template: SNAPSHOT-{{ .Commit }}

checksum:
  disable: false
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '(?i)^docs?:'
      - '(?i)^docs\([^:]+\):'
      - '(?i)^docs\[[^:]+\]:'
      - '^tests?:'
      - '(?i)^dev:'
      - '(?i)^chore:'
      - '^build\(deps\): bump .* in /docs \(#\d+\)'
      - '^build\(deps\): bump .* in /\.github/peril \(#\d+\)'
      - '^build\(deps\): bump .* in /scripts/gen_github_action_config \(#\d+\)'
      - Merge pull request
      - Merge branch

release:
  skip_upload: false
  github:
    owner: scop
    name: golangci-lint
  header: |
    `golangci-lint` is a free and open-source project built by volunteers.

    If you value it, consider supporting us, the [maintainers](https://opencollective.com/golangci-lint) and [linter authors](https://golangci-lint.run/product/thanks/).

    We appreciate it! :heart:

    For key updates, see the [changelog](https://golangci-lint.run/product/changelog/#{{ .Major }}{{ .Minor }}{{ .Patch }}).

signs:
  - signature: ${artifact}.sigstore.json
    cmd: cosign
    args:
      - sign-blob
      - --bundle=${signature}
      - --new-bundle-format
      - --yes
      - ${artifact}
    artifacts: checksum

source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Version }}-source'

